// export const BASE_URL                = 'http://192.168.100.4/tamu/';
export const BASE_URL                = 'http://192.168.83.137/api/';
// export const BASE_URL                = 'http://192.168.9.91/tamu/';
export const BASE_URL_UPLOAD         = BASE_URL+'api/upload/';
export const API_KEY                 = 'Bearer PPFiRAihvl7Wy97CrTSOJK0VJo3ucjVi1tFXAFkNxEEVbDkpZf';
export const OS_GOOGLEID             = '791116217112';

export const DEFAULT_REQUEST         = 'POST';
export const DEFAULT_TIMEOUT         = 60000;
export const DEFAULT_MAX_FILE_SIZE   = 8000000; // 8MB
export const DEFAULT_DIR_DOWNLOAD    = 'Skuy';
export const DEFAULT_DB_USER         = 'SkuyApp';
export const DEFAULT_DB_HOME         = 'home';
export const DEFAULT_DB_CONNECTION   = 'noConnetion';
export const DEFAULT_DB_EXPIRES      = (1000 * 3600 * 24);
export const DEFAULT_PAGE            = 0;
export const DEFAULT_PERPAGE         = 5;
export const TIMER                   = 60;
export const APP_VERSION             = '2.4';
